[package]
name = "linux_modules"
version = "0.2.4-alpha.0"
authors = ["Diana"]
edition = "2018"
#
description = "Tool To Manage Linux Kernel Modules"
documentation = "https://docs.rs/linux_modules"
repository = "https://github.com/DianaNites/linux_modules"
readme = "README.md"
keywords = [
    "linux",
    "kernel",
    "module",
]
categories = [
    "os::unix-apis",
    "command-line-utilities"
]
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.3.21"
anyhow = "1.0.35"
comfy-table = "1.4.2"
linapi = "0.5.1"
quit = "1.1.2"

[[bin]]
path = "src/main.rs"
name = "nms"

[badges]
maintenance = { status = "experimental" }

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "Unreleased"
replace="{{version}}"

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace="...{{tag_name}}"
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "ReleaseDate"
replace="{{date}}"

[[package.metadata.release.pre-release-replacements]]
file="CHANGELOG.md"
search="<!-- next-header -->"
replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"
exactly=1

[[package.metadata.release.pre-release-replacements]]
file="CHANGELOG.md"
search="<!-- next-url -->"
replace="<!-- next-url -->\n[Unreleased]: https://github.com/DianaNites/{{crate_name}}/compare/{{tag_name}}...HEAD"
exactly=1
