[package]
name = "linux_modules"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"

[dependencies]
structopt = "0.3.9"
anyhow = "1.0.26"
comfy-table = "0.0.7"

[dependencies.linapi]
version = "0.1.2-alpha.0"
path = "../linapi"
